// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyLaNtAJnG9FOhIZmIphUu5jYDGVjMsVA',
    appId: '1:84968602660:web:4d712b027d429ee1b06cb1',
    messagingSenderId: '84968602660',
    projectId: 'agendafacil-backend',
    authDomain: 'agendafacil-backend.firebaseapp.com',
    storageBucket: 'agendafacil-backend.firebasestorage.app',
    measurementId: 'G-MD0YHXCTCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0OGLvVFdS5APTi_NhxGw31neBmgJFc_s',
    appId: '1:84968602660:android:fee835e18fb50264b06cb1',
    messagingSenderId: '84968602660',
    projectId: 'agendafacil-backend',
    storageBucket: 'agendafacil-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'SUA_API_KEY_IOS',
    appId: 'APP_ID_IOS',
    messagingSenderId: 'SENDER_IOS',
    projectId: 'PROJECT_ID',
    storageBucket: 'BUCKET',
    iosBundleId: 'BUNDLE_ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'API_KEY_MAC',
    appId: 'APP_ID_MAC',
    messagingSenderId: 'SENDER_MAC',
    projectId: 'PROJECT_ID',
    storageBucket: 'BUCKET',
    iosBundleId: 'BUNDLE_ID_MAC',
  );
}